[env:esp32dev]
platform = espressif32
board = mhetesp32devkit
framework = arduino
monitor_speed = 115200

build_flags =
  -D TINY_GSM_MODEM_SIM808

lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  knolleary/PubSubClient
  vshymanskyy/TinyGSM
