[env:esp32dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_rts = 0
monitor_dtr = 0

build_flags =
  -D TINY_GSM_MODEM_SIM808
  ; ESP32-C3: route Serial output to USB (COM port) instead of UART0 pins
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  knolleary/PubSubClient
  vshymanskyy/TinyGSM
